version: "3.1"
services:

  postgresdb:
    container_name: lmspostgres
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: lmsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1qaz2wsx