server:
  port: 8088
spring:
  application:
    name: auth
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/lmsdb
    username: postgres
    password: 1qaz2wsx
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none