server:
  port: 8088
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/lmsdb
    username: postgres
    password: 1qaz2wsx
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    user: postgres
    password: 1qaz2wsx
    change-log: classpath:db/changelog/Changelog.xml

jwt:
  private:
    key: classpath:/security/rsa.private.pem
  public:
    key: classpath:/security/rsa.public.pem
  expiry: 36000L
